### ISSUE TITLE
CSS: Destacar o campo com foco

### ISSUE THREAD

**Issue by bjverde** [bjverde/formDin#151]
o campo que recebe o foco deve ter um destaque com corres diferentes. As cores a baixo são apenas um sugestão

![image](https://user-images.githubusercontent.com/1070062/56826930-cd63c780-6833-11e9-986a-8fd490afeef8.png)

**Comment by bjverde** [comment]
https://www.w3schools.com/cssref/sel_focus.asp

```css
input:focus {
  background-color: yellow;
}
```
